keys:
  - &host_fufuwuqi age179g8rh48qctuavvycsv8v78rgea3aclfdwepy979fxccewxyx9vqzquy8p

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *host_fufuwuqi
