clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      lfs: false

when:
  - event: push
    branch: [main, develop]
  - event: pull_request
  - event: [manual, cron]

steps:
  - name: notify-pending
    image: bash
    commands:
      - ci/github-status.sh pending
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token

  - name: generate-hosts
    image: bash
    commands:
      - |
        set -euo pipefail
        thefiles='--override-input thefiles github:categoricalcat/the.files'
        nix eval --refresh $thefiles --json .#nixosConfigurations --apply 'c: builtins.attrNames c' | jq -r '.[]' > .hosts
        echo "Discovered hosts:"
        cat .hosts

  - name: fmt
    image: bash
    commands:
      - nix fmt -- --ci

  - name: statix
    image: bash
    depends_on: [fmt]
    commands:
      - nix develop --command statix check .

  - name: deadnix
    image: bash
    depends_on: [statix]
    commands:
      - nix develop --command deadnix --fail .

  - name: flake-check
    image: bash
    depends_on: [deadnix]
    commands:
      - nix flake check --print-build-logs --show-trace

  - name: build
    image: bash
    depends_on: [flake-check, generate-hosts]
    commands:
      - ci/build.sh

  - name: push
    image: bash
    depends_on: [build]
    commands:
      - attic login "$ATTIC_CACHE_NAME" "$ATTIC_INTERNAL_URL" "$ATTIC_TOKEN"
      - |
        set -euo pipefail
        while read -r h; do
          echo
          echo "=== Pushing $h ==="
          attic push "$ATTIC_CACHE_NAME" "result-$h"
        done < .hosts
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token

  - name: notify-success
    image: bash
    depends_on: [push]
    when:
      - status: [success]
    commands:
      - ci/github-status.sh success
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token

  - name: notify-failure
    image: bash
    when:
      - status: [failure]
    commands:
      - ci/github-status.sh failure
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token
