when:
  - event: [manual, push, cron]

steps:
  - name: notify-pending
    image: bash
    commands:
      - ci/github-status.sh pending
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token

  - name: build-and-push
    image: bash
    commands:
      - attic login "$ATTIC_CACHE_NAME" "$ATTIC_INTERNAL_URL" "$ATTIC_TOKEN"
      - |
        set -euo pipefail
        thefiles='--override-input thefiles github:categoricalcat/the.files'
        for h in $(nix eval --refresh $thefiles --json .#nixosConfigurations --apply 'c: builtins.attrNames c' | jq -r '.[]'); do
          nix build --refresh $thefiles --print-build-logs ".#nixosConfigurations.$h.config.system.build.toplevel" --out-link "result-$h"
          attic push "$ATTIC_CACHE_NAME" "result-$h"
        done
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token

  - name: notify-success
    image: bash
    when:
      - status: [success]
    commands:
      - ci/github-status.sh success
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token

  - name: notify-failure
    image: bash
    when:
      - status: [failure]
    commands:
      - ci/github-status.sh failure
    environment:
      GITHUB_STATUS_TOKEN:
        from_secret: github_status_token
