# Main NixOS Configuration
# This file imports all modular configuration files

{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
    # Modular configuration files
    ./boot.nix # Bootloader configuration
    ./desktop.nix # Desktop environment and display settings
    ./locale.nix # Timezone and internationalization
    ./networking.nix # Network configuration and firewall
    ./network-performance.nix # Network performance tuning
    ./packages.nix # System packages
    ./services.nix # System services (SSH, printing, etc.)
    ./users.nix # User accounts and shell configuration
  ];

  # Nixpkgs configuration to handle deprecated packages
  nixpkgs.overlays = [
    (final: prev: {
      # Override androidndkPkgs_23b to use androidndkPkgs_23
      androidndkPkgs_23b = prev.androidndkPkgs_23;
    })
  ];

  # Suppress CUDA warnings by setting minimum version
  nixpkgs.config = {
    allowUnfree = true; # Allow unfree packages
    cudaSupport = false; # Disable CUDA support (NVIDIA-only, not needed for AMD)
    # For AMD GPU compute support, you would use ROCm instead:
    rocmSupport = true; # Enable if you need AMD GPU compute support
  };

  # NixOS version
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.05"; # Did you read the comment?
}
