# Main NixOS Configuration
# This file imports all modular configuration files

{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Modular configuration files
    ./boot.nix # Bootloader configuration
    ./desktop.nix # Desktop environment and display settings
    ./locale.nix # Timezone and internationalization
    ./networking.nix # Network configuration and firewall
    ./packages.nix # System packages
    ./services.nix # System services (SSH, printing, etc.)
    ./users.nix # User accounts and shell configuration
  ];

  # NixOS version
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.05"; # Did you read the comment?
}
