name: flake ci/cd

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: native
    steps:
      - uses: actions/checkout@main
      - run: nix flake check --print-build-logs --show-trace -v

  set-hosts:
    runs-on: native
    outputs:
      hosts: ${{ steps.set-hosts.outputs.hosts }}
    steps:
      - uses: actions/checkout@main
      - id: set-hosts
        run: |
          hosts=$(nix eval --json '.#nixosConfigurations' --apply 'builtins.attrNames')
          echo "hosts=$hosts" >> "$GITHUB_OUTPUT"

  buildepush:
    needs: [check, set-hosts]
    runs-on: native
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        host: ${{ fromJSON(needs.set-hosts.outputs.hosts) }}
    steps:
      - uses: actions/checkout@main
      - run: ci/build.sh ${{ matrix.host }}
      - name: attic push
        env:
          ATTIC_TOKEN: ${{ secrets.attic_token }}
        run: |
          if [ -z "$ATTIC_TOKEN" ]; then
            echo "attic token is empty, exiting..."
            exit 1
          fi

          attic login "$ATTIC_CACHE_NAME" "$ATTIC_INTERNAL_URL" "$ATTIC_TOKEN"
          attic push "$ATTIC_CACHE_NAME:$ATTIC_CACHE_NAME" "result-${{ matrix.host }}"
          echo ">>= pushd ${{ matrix.host }} =<<"
