name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: nix flake check
        run: nix flake check --print-build-logs

      - name: Enforce formatting and lint (treefmt-nix)
        run: nix fmt -- --ci

      - name: Build NixOS - fufuwuqi
        run: nix eval --raw .#nixosConfigurations.fufuwuqi.config.system.build.toplevel.drvPath

      - name: Build NixOS - wsl
        run: nix eval --raw .#nixosConfigurations.wsl.config.system.build.toplevel.drvPath

      # treefmt-nix check is wired into `nix flake check`

