name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake outputs
        run: nix flake check --print-build-logs

      - name: Check formatting and linting
        run: nix fmt -- --ci

      - name: Build NixOS configuration (fufuwuqi)
        run: nix build .#nixosConfigurations.fufuwuqi.config.system.build.toplevel --no-link

      - name: Build NixOS configuration (wsl)
        run: nix build .#nixosConfigurations.wsl.config.system.build.toplevel --no-link

      # treefmt-nix check is wired into `nix flake check`

