name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check flake outputs
        run: nix flake check --print-build-logs

      - name: Check formatting and linting
        run: nix fmt -- --ci

  eval:
    needs: check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        system: [fufuwuqi, fuchuang, fuyidong]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Evaluate NixOS configuration (${{ matrix.system }})
        run: nix eval --raw .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel.drvPath

