name: cursed flake ci/cd

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  builders:
    if: github.actor == github.repository_owner
    timeout-minutes: 5
    runs-on: self-hosted
    outputs:
      flags: ${{ steps.pings.outputs.flags }}
    steps:
      - id: pings
        run: |
          check() { ping -c 1 -W 1 "$1.vpn" >/dev/null 2>&1; }

          flags=""
          for builder in yitaishi; do
            if check "$builder" && check "$builder"; then
              line=$(grep "$builder" /etc/nix/machines || true)
              if [ -n "$line" ]; then
                flags="$flags $line ;"
              fi
            fi
          done

          if [ -n "$flags" ]; then
            echo "flags=--builders '$flags'" >> "$GITHUB_OUTPUT"
          else
            echo "flags=--builders ''" >> "$GITHUB_OUTPUT"
          fi

  check:
    needs: [builders]
    if: github.actor == github.repository_owner
    timeout-minutes: 30
    runs-on: self-hosted
    env:
      BUILDER_FLAGS: ${{ needs.builders.outputs.flags }}
    steps:
      - uses: actions/checkout@main

      - run: nix fmt --refresh --override-input thefiles github:categoricalcat/the.files -- --ci

      - run: nix flake check ${{ env.BUILDER_FLAGS }} --refresh --override-input thefiles github:categoricalcat/the.files --print-build-logs --show-trace

  generate-matrix:
    if: github.actor == github.repository_owner
    timeout-minutes: 10
    runs-on: self-hosted
    outputs:
      hosts: ${{ steps.set-matrix.outputs.hosts }}
    steps:
      - uses: actions/checkout@main
      - id: set-matrix
        run: |
          HOSTS="$(nix eval --refresh --override-input thefiles github:categoricalcat/the.files --json .#nixosConfigurations --apply 'cfgs: builtins.attrNames cfgs')"
          echo "hosts=$HOSTS" >> "$GITHUB_OUTPUT"

  build:
    needs: [check, builders, generate-matrix]
    if: github.actor == github.repository_owner
    timeout-minutes: 120
    runs-on: self-hosted
    env:
      BUILDER_FLAGS: ${{ needs.builders.outputs.flags }}
    strategy:
      matrix:
        host: ${{ fromJson(needs.generate-matrix.outputs.hosts) }}
      fail-fast: true
    steps:
      - uses: actions/checkout@main

      - run: nix build ${{ env.BUILDER_FLAGS }} --refresh --override-input thefiles github:categoricalcat/the.files .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
