name: lucky flake ci

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    if: github.actor == github.repository_owner
    timeout-minutes: 30
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main

      - run: nix fmt --refresh --override-input thefiles github:categoricalcat/the.files -- --ci

      - run: nix flake check --refresh --override-input thefiles github:categoricalcat/the.files --print-build-logs --show-trace

  generate-matrix:
    if: github.actor == github.repository_owner
    timeout-minutes: 10
    runs-on: self-hosted
    outputs:
      hosts: ${{ steps.set-matrix.outputs.hosts }}
    steps:
      - uses: actions/checkout@main
      - id: set-matrix
        run: |
          HOSTS="$(nix eval --refresh --override-input thefiles github:categoricalcat/the.files --json .#nixosConfigurations --apply 'cfgs: builtins.attrNames cfgs')"
          echo "hosts=$HOSTS" >> "$GITHUB_OUTPUT"

  build:
    needs: [check, generate-matrix]
    if: github.actor == github.repository_owner
    timeout-minutes: 120
    runs-on: self-hosted
    strategy:
      matrix:
        host: ${{ fromJson(needs.generate-matrix.outputs.hosts) }}
      fail-fast: true
    steps:
      - uses: actions/checkout@main

      - run: nix build --refresh --override-input thefiles github:categoricalcat/the.files .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
