cloudflare_api_token: |
    CLOUDFLARE_DNS_API_TOKEN=string
github-token: string
passwords:
    yi: string
    workd: string
    nextcloud: string
tokens:
    forgejo-runner: string
    github-runner-nixos: string
    attic-server-jwt-env: |
        ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64=<base64-rsa-key>
    attic-push-token: string
    playit-agent: |
        SECRET_KEY=string
    cloudflared: string
    localtonet-authtoken: string
    deepseek: string

samba:
    credentials:
        yi: |
            username=string
            password=string
services:
    htpasswd: |
        admin:$2y$05$bcrypthashhere
    grafana:
        secret-key: string
