passwords:
    fufud: asdf
    workd: asdf
tokens:
    github-runner-nixos: asdf
    playit-agent: |
        SECRET_KEY=asdf
    wg-easy: |
        PASSWORD_HASH='asdf'
    cloudflare-ddclient: asdf
    cloudflare-acme: asdf
    cloudflared: asdf
ngrok:
    config: |
        agent:
          authtoken: asdf
        version: "3"