passwords:
    fufud: string
    workd: string
tokens:
    github-runner-nixos: string
    playit-agent: |
        SECRET_KEY=string
    wg-easy: |
        PASSWORD_HASH=string
    cloudflare-ddclient: string
    cloudflare-acme: string
    cloudflared: string
joplin-env: |
    DB_CLIENT=mysql
    POSTGRES_PASSWORD=string
    POSTGRES_USER=joplin
    POSTGRES_DATABASE=joplin
    POSTGRES_PORT=3306
    POSTGRES_HOST=10.100.0.1
    APP_BASE_URL=http://joplin.fufu.land:22300
    APP_PORT=22300
ngrok:
    config: |-
        agent:
          authtoken: string
        version: "3"
samba:
    credentials:
        fufud: |
            username=string
            password=string