passwords:
    yi: string
    workd: string
    nextcloud: string
tokens:
    github-runner-nixos: string
    attic-server-jwt-env: |
        ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64=<base64-rsa-key>
    attic-push-token: string
    playit-agent: |
        SECRET_KEY=string
    cloudflare-acme: string
    cloudflared: string
    localtonet-authtoken: string
    deepseek: string
woodpecker:
    agent-secret: string
    forgejo-client: string
    forgejo-secret: string
samba:
    credentials:
        yi: |
            username=string
            password=string
services:
    htpasswd: |
        admin:$2y$05$bcrypthashhere
netbird:
    setup_key: string
